class ChromeDriverInstaller():
    fullVersion: list[int]
    version: int
    compatibleDriverVersion: str | None
    def __init__(self) -> ChromeDriverInstaller: ...
    def getCompatibleDriverVersion(self) -> str | None: ...
    def installCompatibleDriver(self) -> None: ...
    def autoInstall(self) -> None: ...
    @staticmethod
    def waitUntilDriverInstall() -> None: ...
